version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: avivedaherbals-mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - /mnt/mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  django:
    build: .
    container_name: avivedaherbals-django
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
