name: CI - Build & Test Django

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django checks and tests
        run: |
          python manage.py check
          python manage.py test

  notify:
    needs: build-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send Success Email
        if: ${{ needs.build-test.result == 'success' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "CI Success - Aviveda Herbals"
          to: ${{secrets.NOTIFICATION_EMAILS}}
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Hi,

            The CI build for *Aviveda Herbals* completed successfully!

            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Commit Message: ${{ github.event.head_commit.message }}
            Repository: ${{ github.repository }}
            Triggered by: ${{ github.actor }}

            Regards,  
            Hassle Free Enterprise

      - name: Send Failure Email
        if: ${{ needs.build-test.result == 'failure' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "CI Failed - Aviveda Herbals"
          to:  ${{secrets.NOTIFICATION_EMAILS}}
          from: ${{ secrets.EMAIL_USER }}
          body: |
            Hi,

            The CI build for Aviveda Herbals has failed.

            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Commit Message: ${{ github.event.head_commit.message }}
            Repository: ${{ github.repository }}
            Triggered by: ${{ github.actor }}

            Please check the logs in GitHub Actions for details.

            Regards,  
            Hassle Free Enterprise
