# Generated by Django 5.2.5 on 2025-09-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_cart'),
        ('products', '0002_alter_product_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
